name: Singularity CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
          
      - name: Build Singularity SIF image
        run: sudo $(which singularity) build containers-example-${{ github.sha }}.sif Singularity.def

      - name: Run Singularity Container
        run: singularity run containers-example-${{ github.sha }}.sif test2.jpg
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ascii-art-output
          path: ./out.txt
